accent = "#5e81ac"
cursor = "#1c2d28"
foreground = "#1c2d28"
background = "#dfe4c4"
selection_foreground = "#1c2d28"
selection_background = "#5e81ac"

color0 = "#dfe4c4"
color1 = "#bf616a"
color2 = "#5f745d"
color3 = "#d08770"
color4 = "#5e81ac"
color5 = "#b48ead"
color6 = "#4a8c99"
color7 = "#384f54"
color8 = "#5f8170"
color9 = "#bf616a"
color10 = "#6b8c4f"
color11 = "#d08770"
color12 = "#5e81ac"
color13 = "#b48ead"
color14 = "#4a8c99"
color15 = "#1c2d28"
